/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iHom3ProfileSol from "./IHom3Profile.sol";
export type { iHom3ProfileSol };
export type { IBlockSales } from "./IBlockSales";
export type { IBlockStore } from "./IBlockStore";
export type { IBlockToken } from "./IBlockToken";
export type { IERC20 } from "./IERC20";
export type { IGhoToken } from "./IGhoToken";
export type { IWallGenerator } from "./IWallGenerator";
