/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stInrwlTokenSol from "./stINRWLToken.sol";
export type { stInrwlTokenSol };
export type { BlockToken } from "./BlockToken";
export type { InnerBlockToken } from "./InnerBlockToken";
