/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as innerBlockSol from "./InnerBlock.sol";
export type { innerBlockSol };
import type * as security from "./security";
export type { security };
import type * as utils from "./utils";
export type { utils };
export type { BlockSales } from "./BlockSales";
export type { BlockToken } from "./BlockToken";
export type { Lock } from "./Lock";
