/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Hom3PageMessaging,
  Hom3PageMessagingInterface,
} from "../../../../contracts/helpers/ValutMessageHandler.sol/Hom3PageMessaging";

const _abi = [
  {
    inputs: [],
    name: "BalanceToLow",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOwnerOfProfile",
    type: "error",
  },
  {
    inputs: [],
    name: "VaultBalanceToLow",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "DepositedFunds",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "messageId_",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "DepositedFundsRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "WithdrewFunds",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "messageId_",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "WithdrewFundsRequested",
    type: "event",
  },
] as const;

export class Hom3PageMessaging__factory {
  static readonly abi = _abi;
  static createInterface(): Hom3PageMessagingInterface {
    return new Interface(_abi) as Hom3PageMessagingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Hom3PageMessaging {
    return new Contract(address, _abi, runner) as unknown as Hom3PageMessaging;
  }
}
