/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlockToken,
  IBlockTokenInterface,
} from "../../../contracts/interfaces/IBlockToken";

const _abi = [
  {
    inputs: [],
    name: "InnerWallNotEmpty",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOwnerOfToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "salesContract_",
        type: "address",
      },
    ],
    name: "mintAllBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlockToken__factory {
  static readonly abi = _abi;
  static createInterface(): IBlockTokenInterface {
    return new Interface(_abi) as IBlockTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBlockToken {
    return new Contract(address, _abi, runner) as unknown as IBlockToken;
  }
}
