/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultData,
  IVaultDataInterface,
} from "../../../contracts/interfaces/IVaultData";

const _abi = [
  {
    inputs: [],
    name: "BalanceToLow",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOwnerOfProfile",
    type: "error",
  },
  {
    inputs: [],
    name: "VaultBalanceToLow",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "DepositedFunds",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "messageId_",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "DepositedFundsRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to_",
        type: "address",
      },
    ],
    name: "ProfileOwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "WithdrewFunds",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "messageId_",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId_",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "WithdrewFundsRequested",
    type: "event",
  },
] as const;

export class IVaultData__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultDataInterface {
    return new Interface(_abi) as IVaultDataInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVaultData {
    return new Contract(address, _abi, runner) as unknown as IVaultData;
  }
}
